// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: dispatcher.proto

package dispatcher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunJobRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Payload            []byte                 `protobuf:"bytes,2,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	Priority           *int64                 `protobuf:"varint,3,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	Entrypoint         []string               `protobuf:"bytes,4,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	IdleTimeoutSeconds *float32               `protobuf:"fixed32,5,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3,oneof" json:"idle_timeout_seconds,omitempty"`
	MaxAttempts        *float32               `protobuf:"fixed32,6,opt,name=max_attempts,json=maxAttempts,proto3,oneof" json:"max_attempts,omitempty"`
	TimeoutSeconds     *float32               `protobuf:"fixed32,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3,oneof" json:"timeout_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunJobRequest) Reset() {
	*x = RunJobRequest{}
	mi := &file_dispatcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobRequest) ProtoMessage() {}

func (x *RunJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobRequest.ProtoReflect.Descriptor instead.
func (*RunJobRequest) Descriptor() ([]byte, []int) {
	return file_dispatcher_proto_rawDescGZIP(), []int{0}
}

func (x *RunJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunJobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunJobRequest) GetPriority() int64 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *RunJobRequest) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *RunJobRequest) GetIdleTimeoutSeconds() float32 {
	if x != nil && x.IdleTimeoutSeconds != nil {
		return *x.IdleTimeoutSeconds
	}
	return 0
}

func (x *RunJobRequest) GetMaxAttempts() float32 {
	if x != nil && x.MaxAttempts != nil {
		return *x.MaxAttempts
	}
	return 0
}

func (x *RunJobRequest) GetTimeoutSeconds() float32 {
	if x != nil && x.TimeoutSeconds != nil {
		return *x.TimeoutSeconds
	}
	return 0
}

type RunJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobResponse) Reset() {
	*x = RunJobResponse{}
	mi := &file_dispatcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobResponse) ProtoMessage() {}

func (x *RunJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobResponse.ProtoReflect.Descriptor instead.
func (*RunJobResponse) Descriptor() ([]byte, []int) {
	return file_dispatcher_proto_rawDescGZIP(), []int{1}
}

func (x *RunJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_dispatcher_proto protoreflect.FileDescriptor

const file_dispatcher_proto_rawDesc = "" +
	"\n" +
	"\x10dispatcher.proto\x12\x13wardu.dispatcher.v1\"\xea\x02\n" +
	"\rRunJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\apayload\x18\x02 \x01(\fH\x00R\apayload\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x03 \x01(\x03H\x01R\bpriority\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x04 \x03(\tR\n" +
	"entrypoint\x125\n" +
	"\x14idle_timeout_seconds\x18\x05 \x01(\x02H\x02R\x12idleTimeoutSeconds\x88\x01\x01\x12&\n" +
	"\fmax_attempts\x18\x06 \x01(\x02H\x03R\vmaxAttempts\x88\x01\x01\x12,\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x02H\x04R\x0etimeoutSeconds\x88\x01\x01B\n" +
	"\n" +
	"\b_payloadB\v\n" +
	"\t_priorityB\x17\n" +
	"\x15_idle_timeout_secondsB\x0f\n" +
	"\r_max_attemptsB\x12\n" +
	"\x10_timeout_seconds\"?\n" +
	"\x0eRunJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2f\n" +
	"\x11DispatcherService\x12Q\n" +
	"\x06RunJob\x12\".wardu.dispatcher.v1.RunJobRequest\x1a#.wardu.dispatcher.v1.RunJobResponseB$Z\"shared/proto/dispatcher;dispatcherb\x06proto3"

var (
	file_dispatcher_proto_rawDescOnce sync.Once
	file_dispatcher_proto_rawDescData []byte
)

func file_dispatcher_proto_rawDescGZIP() []byte {
	file_dispatcher_proto_rawDescOnce.Do(func() {
		file_dispatcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dispatcher_proto_rawDesc), len(file_dispatcher_proto_rawDesc)))
	})
	return file_dispatcher_proto_rawDescData
}

var file_dispatcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dispatcher_proto_goTypes = []any{
	(*RunJobRequest)(nil),  // 0: wardu.dispatcher.v1.RunJobRequest
	(*RunJobResponse)(nil), // 1: wardu.dispatcher.v1.RunJobResponse
}
var file_dispatcher_proto_depIdxs = []int32{
	0, // 0: wardu.dispatcher.v1.DispatcherService.RunJob:input_type -> wardu.dispatcher.v1.RunJobRequest
	1, // 1: wardu.dispatcher.v1.DispatcherService.RunJob:output_type -> wardu.dispatcher.v1.RunJobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dispatcher_proto_init() }
func file_dispatcher_proto_init() {
	if File_dispatcher_proto != nil {
		return
	}
	file_dispatcher_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dispatcher_proto_rawDesc), len(file_dispatcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dispatcher_proto_goTypes,
		DependencyIndexes: file_dispatcher_proto_depIdxs,
		MessageInfos:      file_dispatcher_proto_msgTypes,
	}.Build()
	File_dispatcher_proto = out.File
	file_dispatcher_proto_goTypes = nil
	file_dispatcher_proto_depIdxs = nil
}
