// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: scheduler.proto

package scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJobRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Image              string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Payload            []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority           int64                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Autorun            bool                   `protobuf:"varint,4,opt,name=autorun,proto3" json:"autorun,omitempty"`
	Entrypoint         []string               `protobuf:"bytes,5,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	IdleTimeoutSeconds float32                `protobuf:"fixed32,6,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	MaxAttempts        float32                `protobuf:"fixed32,7,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Namespace          string                 `protobuf:"bytes,8,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TimeoutSeconds     float32                `protobuf:"fixed32,9,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJobRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateJobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateJobRequest) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateJobRequest) GetAutorun() bool {
	if x != nil {
		return x.Autorun
	}
	return false
}

func (x *CreateJobRequest) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *CreateJobRequest) GetIdleTimeoutSeconds() float32 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *CreateJobRequest) GetMaxAttempts() float32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *CreateJobRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateJobRequest) GetTimeoutSeconds() float32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CreateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobResponse) Reset() {
	*x = CreateJobResponse{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobResponse) ProtoMessage() {}

func (x *CreateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobResponse.ProtoReflect.Descriptor instead.
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\x12wardu.scheduler.v1\"\xb4\x02\n" +
	"\x10CreateJobRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x03R\bpriority\x12\x18\n" +
	"\aautorun\x18\x04 \x01(\bR\aautorun\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x05 \x03(\tR\n" +
	"entrypoint\x120\n" +
	"\x14idle_timeout_seconds\x18\x06 \x01(\x02R\x12idleTimeoutSeconds\x12!\n" +
	"\fmax_attempts\x18\a \x01(\x02R\vmaxAttempts\x12\x1c\n" +
	"\tnamespace\x18\b \x01(\tR\tnamespace\x12'\n" +
	"\x0ftimeout_seconds\x18\t \x01(\x02R\x0etimeoutSeconds\"*\n" +
	"\x11CreateJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId2l\n" +
	"\x10SchedulerService\x12X\n" +
	"\tCreateJob\x12$.wardu.scheduler.v1.CreateJobRequest\x1a%.wardu.scheduler.v1.CreateJobResponseB\"Z shared/proto/scheduler;schedulerb\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scheduler_proto_goTypes = []any{
	(*CreateJobRequest)(nil),  // 0: wardu.scheduler.v1.CreateJobRequest
	(*CreateJobResponse)(nil), // 1: wardu.scheduler.v1.CreateJobResponse
}
var file_scheduler_proto_depIdxs = []int32{
	0, // 0: wardu.scheduler.v1.SchedulerService.CreateJob:input_type -> wardu.scheduler.v1.CreateJobRequest
	1, // 1: wardu.scheduler.v1.SchedulerService.CreateJob:output_type -> wardu.scheduler.v1.CreateJobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
