apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "development"
  GATEWAY_HTTP_PORT: "8080"
  SCHEDULER_GRPC_ADDR: "scheduler-service:8081"
  SCHEDULER_GRPC_PORT: ":8081"
  DISPATCHER_GRPC_ADDR: "scheduler-service:8082"
  DISPATCHER_GRPC_PORT: ":8082"
  POSTGRES_DATABASE: wardu
  POSTGRES_USERNAME: wardu
  POSTGRES_PASSWORD: wardu
  POSTGRES_HOST: postgres.default.svc.cluster.local
  POSTGRES_PORT: "5432"
