apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-service
  template:
    metadata:
      labels:
        app: scheduler-service
    spec:
      containers:
        - name: scheduler-service
          image: wardu/scheduler-service:v1
          ports:
            - containerPort: 8081
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            # Accessing an env variable from the app-config config map
            - name: SCHEDULER_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  key: SCHEDULER_GRPC_PORT
                  name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  selector:
    app: scheduler-service
  ports:
    - port: 8081
      name: grpc
      targetPort: 8081
  type: ClusterIP
